### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by dpugeau** [madsailor/SMF-Extension#1]
Hi Madsailor,  I just downloaded and installed SMF.  I initially had an error in the extension manager but a google search brought the libreoffice-pyuno package to my attention.  After installing it the install appears to have worked.

I next opened the yahooexamples.ods.  It shows #VALUE! for every formula.  Same for both Morningstar sample spreadsheets.

I've tried the extension on LibreOffice 4.1.6.2 on Fedora 19 and on OpenOffice 4.1.0 on Red Hat 6.5.  Same results on both.

Any help troubleshooting would be appreciated.

**Comment by ranoniem** [comment]
Thanks, its working!

LibreOffice Version: 4.3.3.2
(g)Ubuntu 14.10 64-bit

**Comment by madsailor** [comment]
Great. Thanks for the feedback!
