### ISSUE TITLE
Currency exchange rates

### ISSUE THREAD

**Issue by escrow33** [madsailor/SMF-Extension#7]
Not so much an issue, more a suggestion. You might want to promote the fact that the GetYahoo function can also be used to get currency exchange rates as it is, without change.
Just change ticker to something like "GBPUSD=X" or "AUDJPY=X" with Datacode of something like 5.

e.g. GETYAHOO(A1,Datacode)  where A1 = "USDEUR=X"

 Dividend Yield 1   N/A
 Dividend per Share 2   N/A
 Dividend Pay Date  3   N/A
 Ex-Dividend Date   4   N/A
 Previous Close 5   0.9069
 Open   6   0.9069
 Change 7   -0.0083
 Last Trade Date    8   8/19/2015
 Change & Percent Change    9   -0.0083 - -0.9166%
 Last Trade Time    10  8:27pm
etc.

Incidentally - thanks for SMF. I've just recently abandoned Windows & started using Ubuntu.
Had my first foray into python by adding GetYahooHistorical to your extension. It works, though being my first probably a bit ropey.

**Comment by DarkSkySteve** [comment]
Awesome...looking for exactly this! Thanks

**Comment by escrow33** [comment]
More than a year on, still newbie to Github, but as I said in the first sentence of my first post, not an issue, so I guess I should press the 'Close issue' button.
